services:
  traefik:
    image: traefik:v3.3
    volumes:
      - ./test/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./test/dynamic:/etc/traefik/dynamic
      - ./test/certs:/etc/traefik/certs:ro
      - .:/plugins-local/src/github.com/kumojin/traefik-sni:ro
    ports:
      - "443:443"
    depends_on:
      - legit
      - victim

  legit:
    image: traefik/whoami
    command: --name legit

  victim:
    image: traefik/whoami
    command: --name victim
